# Generated by Django 5.0.3 on 2024-03-23 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image1_comparisons', to='ranking.image')),
                ('image2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image2_comparisons', to='ranking.image')),
                ('preferred_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_comparisons', to='ranking.image')),
            ],
        ),
    ]
