# Generated by Django 5.0.3 on 2024-03-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
