# Generated by Django 5.0.3 on 2024-03-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0004_alter_image_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparisonresult',
            name='preferred_image',
        ),
        migrations.AddField(
            model_name='comparisonresult',
            name='winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comparison_winner', to='ranking.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='image1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_image1', to='ranking.image'),
        ),
        migrations.AlterField(
            model_name='comparisonresult',
            name='image2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_image2', to='ranking.image'),
        ),
    ]
